import { query } from "@/lib/db"
import type { ChatMessage, FitnessMemorySnapshot } from "@/lib/fitness-ai/types"

let schemaReady: Promise<void> | null = null

export function ensureFitnessAiSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = (async () => {
      try {
        await query(`
          CREATE TABLE IF NOT EXISTS fitness_ai_memory (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            academia_id INTEGER NOT NULL REFERENCES academias(id) ON DELETE CASCADE,
            messages_json TEXT NOT NULL DEFAULT '[]',
            context_snapshot TEXT,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fitness_ai_memory_user UNIQUE (user_id, academia_id)
          )
        `)
      } catch (e) {
        console.warn("[fitness-ai] schema:", e instanceof Error ? e.message : e)
      }
    })()
  }
  return schemaReady
}

export async function loadChatHistory(
  userId: number,
  academiaId: number,
  limit = 24,
): Promise<ChatMessage[]> {
  await ensureFitnessAiSchema()
  try {
    const rows = await query<{ messages_json: string }>(
      `SELECT messages_json FROM fitness_ai_memory WHERE user_id = ? AND academia_id = ? LIMIT 1`,
      [userId, academiaId],
    )
    const raw = rows[0]?.messages_json
    if (!raw) return []
    const parsed = JSON.parse(raw) as ChatMessage[]
    if (!Array.isArray(parsed)) return []
    return parsed.slice(-limit)
  } catch {
    return []
  }
}

export async function saveChatHistory(
  userId: number,
  academiaId: number,
  messages: ChatMessage[],
  snapshot?: FitnessMemorySnapshot,
): Promise<void> {
  await ensureFitnessAiSchema()
  const trimmed = messages.slice(-40)
  const json = JSON.stringify(trimmed)
  const snap = snapshot ? JSON.stringify(snapshot) : null
  try {
    await query(
      `INSERT INTO fitness_ai_memory (user_id, academia_id, messages_json, context_snapshot, updated_at)
       VALUES (?, ?, ?, ?, now())
       ON CONFLICT (user_id, academia_id) DO UPDATE SET
         messages_json = EXCLUDED.messages_json,
         context_snapshot = EXCLUDED.context_snapshot,
         updated_at = now()`,
      [userId, academiaId, json, snap],
    )
  } catch (e) {
    console.warn("[fitness-ai] save history:", e instanceof Error ? e.message : e)
  }
}

export async function loadMemorySnapshot(
  userId: number,
  academiaId: number,
): Promise<FitnessMemorySnapshot | null> {
  await ensureFitnessAiSchema()
  try {
    const rows = await query<{ context_snapshot: string | null }>(
      `SELECT context_snapshot FROM fitness_ai_memory WHERE user_id = ? AND academia_id = ? LIMIT 1`,
      [userId, academiaId],
    )
    const raw = rows[0]?.context_snapshot
    if (!raw) return null
    return JSON.parse(raw) as FitnessMemorySnapshot
  } catch {
    return null
  }
}
