import { execute } from "@/lib/db"

/**
 * Cria a tabela `treinos` se ainda não existir (Supabase PostgreSQL).
 */
export async function ensureTreinosTable(): Promise<void> {
  const ddl = `
CREATE TABLE IF NOT EXISTS treinos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id INTEGER NOT NULL REFERENCES academias (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
  nome VARCHAR(200) NOT NULL,
  categoria VARCHAR(80),
  status VARCHAR(40) NOT NULL DEFAULT 'ativo',
  exercicios TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
  `.trim()

  await execute(ddl, [])
}
