import { query, insertRow } from "@/lib/db"
import type { JwtPayloadUser } from "@/lib/auth/jwt"
import type { PerfilTreinoInteligente, SexoAluno, NivelAluno } from "@/lib/treino-inteligente/generator"

export type AlunoRecord = {
  id: number
  nome: string
  email: string | null
  peso: number | null
  altura: number | null
  objetivo: string | null
  idade: number | null
  sexo: string | null
  nivel: string | null
  frequencia_semanal: number | null
  limitacoes: string | null
  percentual_gordura: number | null
  usuario_id: number | null
}

let schemaReady: Promise<void> | null = null

export function ensureTreinoInteligenteSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = (async () => {
      const alters = [
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS usuario_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS idade INTEGER",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS sexo VARCHAR(20)",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS nivel VARCHAR(40)",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS frequencia_semanal INTEGER",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS limitacoes TEXT",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS percentual_gordura NUMERIC(5,2)",
      ]
      for (const sql of alters) {
        try {
          await query(sql)
        } catch {
          /* coluna já existe */
        }
      }
      try {
        await query(`
          CREATE TABLE IF NOT EXISTS treino_inteligente_historico (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            academia_id INTEGER NOT NULL REFERENCES academias(id) ON DELETE CASCADE,
            imc NUMERIC(5,2),
            progresso_pct INTEGER,
            payload TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
          )
        `)
      } catch {
        /* ignore */
      }
    })()
  }
  return schemaReady
}

export async function resolveAlunoForUser(session: JwtPayloadUser): Promise<AlunoRecord | null> {
  await ensureTreinoInteligenteSchema()

  const byUser = await query<AlunoRecord>(
    `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
     FROM alunos WHERE academia_id = ? AND usuario_id = ? LIMIT 1`,
    [session.academiaId, session.userId],
  )
  if (byUser[0]) return byUser[0]

  const email = session.email?.trim().toLowerCase()
  if (email) {
    const byEmail = await query<AlunoRecord>(
      `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
       FROM alunos WHERE academia_id = ? AND LOWER(email) = ? LIMIT 1`,
      [session.academiaId, email],
    )
    if (byEmail[0]) {
      try {
        await query(`UPDATE alunos SET usuario_id = ? WHERE id = ?`, [session.userId, byEmail[0].id])
      } catch {
        /* coluna ausente */
      }
      return { ...byEmail[0], usuario_id: session.userId }
    }
  }

  const usuario = await query<{ nome: string; email: string }>(
    `SELECT nome, email FROM usuarios WHERE id = ? LIMIT 1`,
    [session.userId],
  )
  const u = usuario[0]
  if (!u) return null

  const id = await insertRow(
    `INSERT INTO alunos (academia_id, nome, email, status, objetivo, nivel, frequencia_semanal, usuario_id)
     VALUES (?, ?, ?, 'ativo', 'Hipertrofia', 'iniciante', 3, ?)`,
    [session.academiaId, u.nome, u.email ?? email, session.userId],
  )

  const created = await query<AlunoRecord>(
    `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
     FROM alunos WHERE id = ? LIMIT 1`,
    [id],
  )
  return created[0] ?? null
}

export function alunoToPerfil(aluno: AlunoRecord): PerfilTreinoInteligente {
  return {
    peso_kg: Number(aluno.peso) || 70,
    altura_cm: Number(aluno.altura) || 170,
    idade: Number(aluno.idade) || 25,
    sexo: (aluno.sexo as SexoAluno) || "outro",
    objetivo: aluno.objetivo?.trim() || "Hipertrofia",
    nivel: (aluno.nivel as NivelAluno) || "iniciante",
    frequencia_semanal: Number(aluno.frequencia_semanal) || 3,
    limitacoes: aluno.limitacoes,
    percentual_gordura: aluno.percentual_gordura != null ? Number(aluno.percentual_gordura) : null,
  }
}

export async function saveAlunoPerfil(alunoId: number, perfil: Partial<PerfilTreinoInteligente>) {
  await query(
    `UPDATE alunos SET
      peso = COALESCE(?, peso),
      altura = COALESCE(?, altura),
      idade = COALESCE(?, idade),
      sexo = COALESCE(?, sexo),
      objetivo = COALESCE(?, objetivo),
      nivel = COALESCE(?, nivel),
      frequencia_semanal = COALESCE(?, frequencia_semanal),
      limitacoes = COALESCE(?, limitacoes),
      percentual_gordura = COALESCE(?, percentual_gordura),
      updated_at = now()
     WHERE id = ?`,
    [
      perfil.peso_kg ?? null,
      perfil.altura_cm ?? null,
      perfil.idade ?? null,
      perfil.sexo ?? null,
      perfil.objetivo ?? null,
      perfil.nivel ?? null,
      perfil.frequencia_semanal ?? null,
      perfil.limitacoes ?? null,
      perfil.percentual_gordura ?? null,
      alunoId,
    ],
  )
}
