import { query, insertRow } from "@/lib/db"
import { resolveDbConfig } from "@/lib/db-config"
import { quoteIdent } from "@/lib/db-dialect"
import { isMissingColumn } from "@/lib/db-errors"
import type { JwtPayloadUser } from "@/lib/auth/jwt"
import type { PerfilTreinoInteligente } from "@/lib/treino-inteligente/generator"
import { normalizeGorduraOpcional, normalizePerfil } from "@/lib/treino-inteligente/perfil-schema"

export type AlunoRecord = {
  id: number
  nome: string
  email: string | null
  peso: number | null
  altura: number | null
  objetivo: string | null
  idade: number | null
  sexo: string | null
  nivel: string | null
  frequencia_semanal: number | null
  limitacoes: string | null
  percentual_gordura: number | null
  usuario_id: number | null
}

let schemaReady: Promise<void> | null = null
let alunosColumnsCache: Map<string, string> | null = null

function sqlFiniteNumber(value: number | null | undefined): number | null {
  if (value === null || value === undefined) return null
  if (!Number.isFinite(value)) return null
  return value
}

async function loadAlunosColumnMap(): Promise<Map<string, string>> {
  if (alunosColumnsCache) return alunosColumnsCache
  const schema = resolveDbConfig().schema
  const cols = await query<{ column_name: string }>(
    `SELECT column_name FROM information_schema.columns
     WHERE table_schema = ? AND LOWER(table_name) = 'alunos'`,
    [schema],
  )
  alunosColumnsCache = new Map(cols.map((c) => [c.column_name.toLowerCase(), c.column_name]))
  return alunosColumnsCache
}

export function ensureTreinoInteligenteSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = (async () => {
      const alters = [
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS usuario_id INTEGER REFERENCES usuarios(id) ON DELETE SET NULL",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS idade INTEGER",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS sexo VARCHAR(20)",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS nivel VARCHAR(40)",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS frequencia_semanal INTEGER",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS limitacoes TEXT",
        "ALTER TABLE alunos ADD COLUMN IF NOT EXISTS percentual_gordura NUMERIC(5,2)",
      ]
      for (const sql of alters) {
        try {
          await query(sql)
        } catch (e) {
          console.warn("[aluno-record] alter skip:", e instanceof Error ? e.message : e)
        }
      }
      alunosColumnsCache = null
      try {
        await query(`
          CREATE TABLE IF NOT EXISTS treino_inteligente_historico (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
            academia_id INTEGER NOT NULL REFERENCES academias(id) ON DELETE CASCADE,
            imc NUMERIC(5,2),
            progresso_pct INTEGER,
            payload TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
          )
        `)
      } catch (e) {
        console.warn("[aluno-record] historico table:", e instanceof Error ? e.message : e)
      }
    })()
  }
  return schemaReady
}

export async function resolveAlunoForUser(session: JwtPayloadUser): Promise<AlunoRecord | null> {
  await ensureTreinoInteligenteSchema()

  const byUser = await query<AlunoRecord>(
    `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
     FROM alunos WHERE academia_id = ? AND usuario_id = ? LIMIT 1`,
    [session.academiaId, session.userId],
  )
  if (byUser[0]) return byUser[0]

  const email = session.email?.trim().toLowerCase()
  if (email) {
    const byEmail = await query<AlunoRecord>(
      `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
       FROM alunos WHERE academia_id = ? AND LOWER(email) = ? LIMIT 1`,
      [session.academiaId, email],
    )
    if (byEmail[0]) {
      const cols = await loadAlunosColumnMap()
      if (cols.has("usuario_id")) {
        try {
          await query(`UPDATE alunos SET usuario_id = ? WHERE id = ?`, [session.userId, byEmail[0].id])
        } catch {
          /* ignore */
        }
      }
      return { ...byEmail[0], usuario_id: session.userId }
    }
  }

  const usuario = await query<{ nome: string; email: string }>(
    `SELECT nome, email FROM usuarios WHERE id = ? LIMIT 1`,
    [session.userId],
  )
  const u = usuario[0]
  if (!u) return null

  const id = await insertRow(
    `INSERT INTO alunos (academia_id, nome, email, status, objetivo, nivel, frequencia_semanal, usuario_id)
     VALUES (?, ?, ?, 'ativo', 'Hipertrofia', 'iniciante', 3, ?)`,
    [session.academiaId, u.nome, u.email ?? email, session.userId],
  )

  const created = await query<AlunoRecord>(
    `SELECT id, nome, email, peso, altura, objetivo, idade, sexo, nivel, frequencia_semanal, limitacoes, percentual_gordura, usuario_id
     FROM alunos WHERE id = ? LIMIT 1`,
    [id],
  )
  return created[0] ?? null
}

export function alunoToPerfil(aluno: AlunoRecord): PerfilTreinoInteligente {
  return normalizePerfil({
    peso_kg: aluno.peso,
    altura_cm: aluno.altura,
    idade: aluno.idade,
    sexo: aluno.sexo,
    objetivo: aluno.objetivo,
    nivel: aluno.nivel,
    frequencia_semanal: aluno.frequencia_semanal,
    limitacoes: aluno.limitacoes,
    percentual_gordura: aluno.percentual_gordura,
  })
}

const PERFIL_COLUMN_MAP: Record<string, (p: PerfilTreinoInteligente) => unknown> = {
  peso: (p) => sqlFiniteNumber(p.peso_kg),
  altura: (p) => sqlFiniteNumber(p.altura_cm),
  idade: (p) => sqlFiniteNumber(p.idade),
  sexo: (p) => p.sexo,
  objetivo: (p) => p.objetivo,
  nivel: (p) => p.nivel,
  frequencia_semanal: (p) => sqlFiniteNumber(p.frequencia_semanal),
  limitacoes: (p) => p.limitacoes ?? null,
  percentual_gordura: (p) => normalizeGorduraOpcional(p.percentual_gordura),
}

export async function saveAlunoPerfil(alunoId: number, perfil: PerfilTreinoInteligente) {
  await ensureTreinoInteligenteSchema()
  const p = normalizePerfil(perfil)
  const cols = await loadAlunosColumnMap()

  const sets: string[] = []
  const params: unknown[] = []

  for (const [field, getter] of Object.entries(PERFIL_COLUMN_MAP)) {
    const actual = cols.get(field)
    if (!actual) continue
    sets.push(`${quoteIdent(actual, "postgres")} = ?`)
    params.push(getter(p))
  }

  if (sets.length === 0) {
    throw new Error("Tabela alunos sem colunas de perfil. Execute npm run db:bootstrap")
  }

  params.push(alunoId)
  const sql = `UPDATE alunos SET ${sets.join(", ")} WHERE id = ?`

  try {
    await query(sql, params)
  } catch (e) {
    if (isMissingColumn(e)) {
      alunosColumnsCache = null
      await ensureTreinoInteligenteSchema()
      throw e
    }
    throw e
  }
}
