-- Memória do Coach IA FitPro (chat + snapshot de contexto)
CREATE TABLE IF NOT EXISTS public.fitness_ai_memory (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES public.usuarios (id) ON DELETE CASCADE,
  academia_id INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  messages_json TEXT NOT NULL DEFAULT '[]',
  context_snapshot TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_fitness_ai_memory_user UNIQUE (user_id, academia_id)
);

CREATE INDEX IF NOT EXISTS idx_fitness_ai_memory_user ON public.fitness_ai_memory (user_id);
