-- =============================================================================
-- FitPro / Academia — schema PostgreSQL completo para Supabase
-- =============================================================================
-- Executar: npm run db:bootstrap   (com DATABASE_URL no .env)
-- Ou: Supabase Dashboard → SQL Editor → colar este ficheiro → Run
--
-- Login: master@academia.com / Master@123
-- =============================================================================

-- Tipos ENUM
DO $$ BEGIN
  CREATE TYPE perfil_usuario AS ENUM ('master', 'admin', 'personal', 'aluno', 'usuario');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE tipo_evento_agenda AS ENUM ('treino', 'avaliacao', 'nutricao');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE status_pagamento AS ENUM ('pago', 'pendente', 'atrasado', 'cancelado');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Função updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- academias
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.academias (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        VARCHAR(200) NOT NULL,
  slug        VARCHAR(80),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_academias_slug UNIQUE (slug)
);

-- -----------------------------------------------------------------------------
-- usuarios (login da app via JWT + bcrypt)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.usuarios (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         VARCHAR(120) NOT NULL,
  email        VARCHAR(160) NOT NULL,
  senha_hash   VARCHAR(255) NOT NULL,
  perfil       perfil_usuario NOT NULL DEFAULT 'aluno',
  ativo        BOOLEAN NOT NULL DEFAULT true,
  academia_id  INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE RESTRICT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_usuarios_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_academia ON public.usuarios (academia_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_email_lower ON public.usuarios (lower(email));

DROP TRIGGER IF EXISTS tr_usuarios_updated_at ON public.usuarios;
CREATE TRIGGER tr_usuarios_updated_at
  BEFORE UPDATE ON public.usuarios
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- usuarios_login_log (auditoria de acessos / logins)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.usuarios_login_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES public.usuarios (id) ON DELETE CASCADE,
  academia_id INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  email       VARCHAR(160) NOT NULL,
  ip          TEXT,
  user_agent  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_usuarios_login_log_created_at ON public.usuarios_login_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_usuarios_login_log_user ON public.usuarios_login_log (academia_id, user_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- alunos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.alunos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id  INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  nome         VARCHAR(120) NOT NULL,
  email        VARCHAR(160),
  telefone     VARCHAR(40),
  objetivo     VARCHAR(255),
  plano        VARCHAR(120),
  status       VARCHAR(40) DEFAULT 'ativo',
  peso         NUMERIC(6, 2),
  altura       NUMERIC(5, 2),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alunos_academia ON public.alunos (academia_id);

DROP TRIGGER IF EXISTS tr_alunos_updated_at ON public.alunos;
CREATE TRIGGER tr_alunos_updated_at
  BEFORE UPDATE ON public.alunos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- treinos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.treinos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id  INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES public.usuarios (id) ON DELETE CASCADE,
  nome         VARCHAR(200) NOT NULL,
  categoria    VARCHAR(80),
  status       VARCHAR(40) NOT NULL DEFAULT 'ativo',
  exercicios   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_treinos_academia ON public.treinos (academia_id);
CREATE INDEX IF NOT EXISTS idx_treinos_user ON public.treinos (user_id);

DROP TRIGGER IF EXISTS tr_treinos_updated_at ON public.treinos;
CREATE TRIGGER tr_treinos_updated_at
  BEFORE UPDATE ON public.treinos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- planos_academia
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planos_academia (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id  INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  slug         VARCHAR(40) NOT NULL,
  nome         VARCHAR(120) NOT NULL,
  valor        NUMERIC(10, 2) NOT NULL,
  duracao      VARCHAR(40) NOT NULL DEFAULT 'Mensal',
  descricao    VARCHAR(255),
  destaque     BOOLEAN NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_planos_acad_slug UNIQUE (academia_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_planos_acad_academia ON public.planos_academia (academia_id);

DROP TRIGGER IF EXISTS tr_planos_academia_updated_at ON public.planos_academia;
CREATE TRIGGER tr_planos_academia_updated_at
  BEFORE UPDATE ON public.planos_academia
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- pagamentos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.pagamentos (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id     INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  aluno_id        INTEGER REFERENCES public.alunos (id) ON DELETE SET NULL,
  aluno_nome      VARCHAR(120) NOT NULL,
  valor           NUMERIC(10, 2) NOT NULL CHECK (valor >= 0),
  vencimento      DATE NOT NULL,
  data_pagamento  DATE,
  status          status_pagamento NOT NULL DEFAULT 'pendente',
  metodo          VARCHAR(60),
  observacoes     VARCHAR(500),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_academia ON public.pagamentos (academia_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_aluno ON public.pagamentos (aluno_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_status ON public.pagamentos (academia_id, status);

DROP TRIGGER IF EXISTS tr_pagamentos_updated_at ON public.pagamentos;
CREATE TRIGGER tr_pagamentos_updated_at
  BEFORE UPDATE ON public.pagamentos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- agenda_eventos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.agenda_eventos (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id   INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  data_evento   DATE NOT NULL,
  horario       VARCHAR(5) NOT NULL,
  tipo          tipo_evento_agenda NOT NULL,
  aluno_nome    VARCHAR(120) NOT NULL,
  aluno_id      INTEGER REFERENCES public.alunos (id) ON DELETE SET NULL,
  duracao       INTEGER NOT NULL DEFAULT 60 CHECK (duracao > 0),
  observacoes   VARCHAR(500),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agenda_academia_data ON public.agenda_eventos (academia_id, data_evento);
CREATE INDEX IF NOT EXISTS idx_agenda_aluno ON public.agenda_eventos (aluno_id);

DROP TRIGGER IF EXISTS tr_agenda_eventos_updated_at ON public.agenda_eventos;
CREATE TRIGGER tr_agenda_eventos_updated_at
  BEFORE UPDATE ON public.agenda_eventos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- dietas + alimentos (módulo nutrição)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dietas (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id     INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  aluno_id        INTEGER REFERENCES public.alunos (id) ON DELETE SET NULL,
  titulo          VARCHAR(200) NOT NULL,
  aluno_nome      VARCHAR(120),
  objetivo        VARCHAR(255),
  proteinas       INTEGER NOT NULL DEFAULT 0 CHECK (proteinas >= 0),
  carbos          INTEGER NOT NULL DEFAULT 0 CHECK (carbos >= 0),
  gorduras        INTEGER NOT NULL DEFAULT 0 CHECK (gorduras >= 0),
  refeicoes_json  TEXT NOT NULL DEFAULT '[]',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dietas_academia ON public.dietas (academia_id);
CREATE INDEX IF NOT EXISTS idx_dietas_aluno ON public.dietas (aluno_id);

DROP TRIGGER IF EXISTS tr_dietas_updated_at ON public.dietas;
CREATE TRIGGER tr_dietas_updated_at
  BEFORE UPDATE ON public.dietas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.alimentos (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academia_id      INTEGER NOT NULL REFERENCES public.academias (id) ON DELETE CASCADE,
  nome             VARCHAR(200) NOT NULL,
  kcal_100g        INTEGER NOT NULL CHECK (kcal_100g >= 0),
  proteinas_100g   NUMERIC(6, 2) NOT NULL DEFAULT 0,
  carbos_100g      NUMERIC(6, 2) NOT NULL DEFAULT 0,
  gorduras_100g    NUMERIC(6, 2) NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_alimentos_academia_nome UNIQUE (academia_id, nome)
);

CREATE INDEX IF NOT EXISTS idx_alimentos_academia ON public.alimentos (academia_id);

DROP TRIGGER IF EXISTS tr_alimentos_updated_at ON public.alimentos;
CREATE TRIGGER tr_alimentos_updated_at
  BEFORE UPDATE ON public.alimentos
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Seeds: academia demo, master, planos, alimentos
-- -----------------------------------------------------------------------------
INSERT INTO public.academias (nome, slug)
VALUES ('Academia Demo', 'academia-demo')
ON CONFLICT (slug) DO NOTHING;

DO $$
DECLARE
  v_academia_id INTEGER;
BEGIN
  SELECT id INTO v_academia_id FROM public.academias ORDER BY id ASC LIMIT 1;
  IF v_academia_id IS NULL THEN
    INSERT INTO public.academias (nome) VALUES ('Academia Demo') RETURNING id INTO v_academia_id;
  END IF;

  INSERT INTO public.usuarios (nome, email, senha_hash, perfil, ativo, academia_id)
  VALUES (
    'Usuario Master',
    'master@academia.com',
    '$2a$10$sBi/Gk7ejnRzfLqz2LMnbuavDy/HQOuZzfx8luX0hcchYUKsHlAy6',
    'master',
    true,
    v_academia_id
  )
  ON CONFLICT (email) DO UPDATE SET
    nome = EXCLUDED.nome,
    senha_hash = EXCLUDED.senha_hash,
    perfil = EXCLUDED.perfil,
    ativo = EXCLUDED.ativo,
    academia_id = EXCLUDED.academia_id,
    updated_at = now();

  INSERT INTO public.planos_academia (academia_id, slug, nome, valor, duracao, descricao, destaque)
  VALUES
    (v_academia_id, 'basico', 'Básico', 89.90, 'Mensal', 'Ideal para quem está começando', false),
    (v_academia_id, 'premium', 'Premium', 189.90, 'Mensal', 'O mais popular entre os alunos', true),
    (v_academia_id, 'vip', 'VIP', 299.90, 'Mensal', 'Experiência completa e exclusiva', false)
  ON CONFLICT (academia_id, slug) DO NOTHING;

  INSERT INTO public.alimentos (academia_id, nome, kcal_100g, proteinas_100g, carbos_100g, gorduras_100g)
  VALUES
    (v_academia_id, 'Macarrão cozido', 160, 5.8, 30.9, 0.9),
    (v_academia_id, 'Carne moída cozida (média gordura)', 250, 26, 0, 16),
    (v_academia_id, 'Arroz branco cozido', 130, 2.5, 28.2, 0.3),
    (v_academia_id, 'Feijão cozido', 77, 4.8, 13.6, 0.5),
    (v_academia_id, 'Frango grelhado', 165, 31, 0, 3.6),
    (v_academia_id, 'Ovo cozido', 155, 13, 1.1, 11),
    (v_academia_id, 'Banana', 89, 1.1, 23, 0.3)
  ON CONFLICT (academia_id, nome) DO NOTHING;
END $$;

-- -----------------------------------------------------------------------------
-- RLS: backend usa connection string postgres (ignora RLS).
-- Desativado para evitar bloqueio com pooler; reative se usar Supabase Client no browser.
-- -----------------------------------------------------------------------------
ALTER TABLE public.academias DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alunos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.treinos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.planos_academia DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.agenda_eventos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.dietas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alimentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios_login_log DISABLE ROW LEVEL SECURITY;
